import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { WideNav } from "@/components/header/wide-nav";

import { ReactLenis } from "@studio-freight/react-lenis";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WideNav />

        {children}
      </body>
    </html>
  );
}
